# Generated by Django 5.2.5 on 2025-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0003_stay_is_demo_stay_latitude_stay_longitude"),
    ]

    operations = []
